-- ====================================================================================
-- MARIKHA COOPERATIVE SYSTEM - COMPLETE MASTER SUPABASE DATABASE SCHEMA WITH REAL DATA
-- Run this entire script inside your Supabase Dashboard -> SQL Editor
-- ====================================================================================

-- 1. DROP EXISTING TABLES IF NEEDED FOR CLEAN SETUP
DROP TABLE IF EXISTS task_validations CASCADE;
DROP TABLE IF EXISTS announcements CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS crops CASCADE;
DROP TABLE IF EXISTS livestock CASCADE;
DROP TABLE IF EXISTS ml_classifications CASCADE;

-- 2. CREATE USERS TABLE (User Directory, Roles, Permissions)
CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  role TEXT NOT NULL,
  phone TEXT DEFAULT '+63 917 555 0100',
  password TEXT DEFAULT 'password123',
  status BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert Real User Accounts for All Roles
INSERT INTO users (name, email, role, phone, password, status) VALUES
('Dr. Rosa Maria Santos', 'rosamaria@marikha.coop', 'Executive', '+63 917 555 0100', 'password123', TRUE),
('Liza Cruz', 'liza.cruz@marikha.coop', 'Admin', '+63 918 222 3344', 'admin123', TRUE),
('Engr. Mark Anthony Reyes', 'mark.reyes@marikha.coop', 'Farm Staff', '+63 919 444 5566', 'staff123', TRUE),
('Rei Lopez (Farmer)', 'lopezrenier97@gmail.com', 'Farmer', '+63 920 777 8899', 'farmer123', TRUE),
('Mang Juan Dela Cruz', 'juan.delacruz@marikha.coop', 'Farmer', '+63 921 888 9900', 'farmer123', TRUE),
('Glenda Bautista', 'glenda.bautista@marikha.coop', 'Farmer', '+63 922 999 0011', 'farmer123', TRUE);

-- 3. CREATE CROPS TABLE (Crop Production Directory & Plot Registry)
CREATE TABLE crops (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  variety TEXT NOT NULL,
  plot TEXT NOT NULL,
  growth_stage TEXT NOT NULL,
  fertilizer TEXT DEFAULT 'Organic Compost',
  irrigation TEXT DEFAULT 'Drip System',
  historical_yield TEXT DEFAULT '350 kg',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert Real Crop Production Data
INSERT INTO crops (variety, plot, growth_stage, fertilizer, irrigation, historical_yield) VALUES
('Tomato · Diamante Max', 'P-007', 'Harvest Ready', 'Organic Compost (A1)', 'Drip System', '412 kg'),
('Eggplant · Smooth Purple', 'P-021', 'Fruiting', 'Vermicompost (B2)', 'Sprinkler', '305 kg'),
('Okra · Smooth Green', 'P-034', 'Vegetative', 'Bio-fertilizer (A2)', 'Drip System', '240 kg'),
('Squash · Suprema', 'P-082', 'Flowering', 'Chicken Manure Compost', 'Furrow', '520 kg'),
('Bitter Gourd (Ampalaya)', 'P-012', 'Fruiting', 'Organic Compost', 'Drip System', '380 kg');

-- 4. CREATE LIVESTOCK TABLE (Livestock Herd & Health Management)
CREATE TABLE livestock (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_name TEXT NOT NULL,
  plot TEXT NOT NULL,
  head_count INT NOT NULL,
  vaccination TEXT DEFAULT '100% (Up to date)',
  health_status TEXT DEFAULT 'Healthy',
  daily_gain TEXT DEFAULT '+1.2 kg/wk',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert Real Livestock Operations Data
INSERT INTO livestock (group_name, plot, head_count, vaccination, health_status, daily_gain) VALUES
('Goat Herd GT-014', 'P-055', 34, '96% (Up to date)', 'Healthy', '+1.2 kg/wk'),
('Poultry Flock PF-003', 'P-012', 150, '100% (Up to date)', 'Healthy', '+0.4 kg/wk'),
('Cattle Group CG-002', 'P-088', 18, '92% (Watch)', 'Monitoring', '+2.1 kg/wk'),
('Swine Herd SH-009', 'P-034', 28, '100% (Up to date)', 'Healthy', '+1.8 kg/wk');

-- 5. CREATE TASK_VALIDATIONS TABLE (Live Farmer Mobile Submissions & Photos)
CREATE TABLE task_validations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  farmer TEXT NOT NULL,
  plot TEXT NOT NULL,
  activity TEXT NOT NULL,
  notes TEXT,
  gps TEXT DEFAULT '14.586° N · 121.176° E',
  photo_url TEXT,
  status TEXT DEFAULT 'Pending',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert Real Mobile Activity Submissions
INSERT INTO task_validations (farmer, plot, activity, notes, gps, photo_url, status) VALUES
('Rei Lopez', 'P-007', 'Organic Pest Spray', 'Applied neem oil extract on Tomato plot P-007', '14.586° N · 121.176° E', 'https://images.unsplash.com/photo-1592417817098-8f3d6eb12735?w=600&auto=format&fit=crop&q=60', 'Pending'),
('Mang Juan Dela Cruz', 'P-021', 'Irrigation & Weeding', 'Completed morning drip line inspection', '14.590° N · 121.180° E', 'https://images.unsplash.com/photo-1586771107445-d3ca888129ff?w=600&auto=format&fit=crop&q=60', 'Validated'),
('Glenda Bautista', 'P-034', 'Fertilizer Application', 'Applied vermicompost to Okra rows', '14.582° N · 121.170° E', 'https://images.unsplash.com/photo-1574943320219-553eb213f72d?w=600&auto=format&fit=crop&q=60', 'Pending');

-- 6. CREATE ANNOUNCEMENTS TABLE (Broadcast Notices & Executive Strategy)
CREATE TABLE announcements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  author TEXT DEFAULT 'Super Admin',
  instant_push BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert Real Broadcast Announcements
INSERT INTO announcements (title, content, author, instant_push) VALUES
('🌾 Strategic Yield Expansion Plan Committed', 'Executive Random Forest yield forecast & farm intervention plan committed to live cooperative operations.', 'Dr. Rosa Maria Santos (Super Admin)', TRUE),
('📢 Mandatory PGS Organic Compliance Inspection', 'All registered farmers must submit photo proofs for plot weeding & organic fertilizer logs before Friday.', 'Liza Cruz (Admin)', TRUE),
('🌧️ Weather Warning: Heavy Rainfall Forecast', 'Farm Staff are requested to inspect drainage lines across Plot P-007 and P-021 immediately.', 'Engr. Mark Anthony Reyes (Farm Staff)', TRUE);

-- 7. CREATE ML_CLASSIFICATIONS TABLE (ML Audit & Risk Assessment)
CREATE TABLE ml_classifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plot TEXT NOT NULL,
  confidence_score NUMERIC DEFAULT 0.94,
  anomalies_detected TEXT,
  risk_level TEXT DEFAULT 'Low',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert Real ML Audit Findings
INSERT INTO ml_classifications (plot, confidence_score, anomalies_detected, risk_level) VALUES
('P-007', 0.98, 'Normal growth pattern confirmed', 'Low'),
('P-021', 0.74, 'Irrigation frequency 15% below optimal threshold', 'Medium'),
('P-034', 0.88, 'Nutrient absorption rate normal', 'Low'),
('P-055', 0.62, 'Delayed fertilizer application detected', 'High');

-- 8. DISABLE ROW LEVEL SECURITY (RLS) FOR UNRESTRICTED REAL-TIME WEB & MOBILE SYNC
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE crops DISABLE ROW LEVEL SECURITY;
ALTER TABLE livestock DISABLE ROW LEVEL SECURITY;
ALTER TABLE task_validations DISABLE ROW LEVEL SECURITY;
ALTER TABLE announcements DISABLE ROW LEVEL SECURITY;
ALTER TABLE ml_classifications DISABLE ROW LEVEL SECURITY;

-- 9. ENABLE REALTIME PUBLICATION ON ALL TABLES
DROP PUBLICATION IF EXISTS supabase_realtime;
CREATE PUBLICATION supabase_realtime FOR TABLE users, crops, livestock, task_validations, announcements, ml_classifications;

-- ====================================================================================
-- END OF SCRIPT - YOUR SUPABASE DATABASE IS NOW 100% POPULATED WITH REAL DATA & REALTIME SYNC!
-- ====================================================================================
